baseURL = 'https://midstall.com'
languageCode = 'en-us'
title = 'Midstall Software'

[[module.imports]]
path = 'github.com/theNewDynamic/gohugo-theme-ananke'

[[params.ananke_socials]]
name = 'twitter'
url = 'https://twitter.com/MidstallSW'

[[params.ananke_socials]]
name = 'github'
url = 'https://github.com/MidstallSoftware'

[[params.ananke_socials]]
name = 'slack'
url = 'https://midstall-software.slack.com'
