apiVersion: v1
kind: Service
metadata:
  name: midstall-website
  namespace: midstall
  annotations:
    external-dns.alpha.kubernetes.io/hostname: midstall.com
spec:
  selector:
    app: midstall-website
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
